/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Tayyibat Dietary System API — Dr. Dhia Al-Awadi
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface RegisterInput {
  /** @minLength 2 */
  name: string;
  email: string;
  /** @minLength 8 */
  password: string;
}

export interface LoginInput {
  email: string;
  password: string;
}

export type UserRole = typeof UserRole[keyof typeof UserRole];


export const UserRole = {
  user: 'user',
  admin: 'admin',
} as const;

export interface User {
  id: number;
  name: string;
  email: string;
  role: UserRole;
  /** @nullable */
  avatarUrl?: string | null;
  createdAt: string;
}

export interface AuthResponse {
  user: User;
  token: string;
}

export type FoodStatus = typeof FoodStatus[keyof typeof FoodStatus];


export const FoodStatus = {
  tayyib: 'tayyib',
  khabeeth: 'khabeeth',
} as const;

export interface Food {
  id: number;
  name: string;
  nameAr: string;
  status: FoodStatus;
  category: string;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  descriptionAr?: string | null;
  /** @nullable */
  notes?: string | null;
}

export interface FoodListResponse {
  items: Food[];
  total: number;
  page: number;
  limit: number;
}

export interface FoodCategory {
  name: string;
  nameAr?: string;
  tayyibCount: number;
  khabeethCount: number;
}

export type TrackerEntryType = typeof TrackerEntryType[keyof typeof TrackerEntryType];


export const TrackerEntryType = {
  meal: 'meal',
  water: 'water',
  fasting: 'fasting',
  symptom: 'symptom',
} as const;

export interface TrackerEntry {
  id: number;
  userId: number;
  type: TrackerEntryType;
  date: string;
  /** @nullable */
  time?: string | null;
  /** @nullable */
  foodName?: string | null;
  /** @nullable */
  foodStatus?: string | null;
  /** @nullable */
  quantity?: string | null;
  /** @nullable */
  notes?: string | null;
  /** @nullable */
  imageUrl?: string | null;
  /** @nullable */
  waterMl?: number | null;
  /** @nullable */
  fastingHours?: number | null;
  /** @nullable */
  hungerLevel?: number | null;
  /** @nullable */
  energyLevel?: number | null;
  createdAt: string;
}

export type TrackerEntryInputType = typeof TrackerEntryInputType[keyof typeof TrackerEntryInputType];


export const TrackerEntryInputType = {
  meal: 'meal',
  water: 'water',
  fasting: 'fasting',
  symptom: 'symptom',
} as const;

export type TrackerEntryInputFoodStatus = typeof TrackerEntryInputFoodStatus[keyof typeof TrackerEntryInputFoodStatus];


export const TrackerEntryInputFoodStatus = {
  tayyib: 'tayyib',
  khabeeth: 'khabeeth',
} as const;

export interface TrackerEntryInput {
  type: TrackerEntryInputType;
  date: string;
  time?: string;
  foodName?: string;
  foodStatus?: TrackerEntryInputFoodStatus;
  quantity?: string;
  notes?: string;
  imageUrl?: string;
  waterMl?: number;
  fastingHours?: number;
  /**
     * @minimum 1
     * @maximum 10
     */
  hungerLevel?: number;
  /**
     * @minimum 1
     * @maximum 10
     */
  energyLevel?: number;
}

export type TrackerEntryUpdateType = typeof TrackerEntryUpdateType[keyof typeof TrackerEntryUpdateType];


export const TrackerEntryUpdateType = {
  meal: 'meal',
  water: 'water',
  fasting: 'fasting',
  symptom: 'symptom',
} as const;

export interface TrackerEntryUpdate {
  type?: TrackerEntryUpdateType;
  date?: string;
  time?: string;
  foodName?: string;
  foodStatus?: string;
  quantity?: string;
  notes?: string;
  imageUrl?: string;
  waterMl?: number;
  fastingHours?: number;
  hungerLevel?: number;
  energyLevel?: number;
}

export interface TodaySummary {
  date: string;
  mealCount: number;
  tayyibCount: number;
  khabeethCount: number;
  waterMl: number;
  fastingHours: number;
  averageHunger: number;
  averageEnergy: number;
  /** Percentage 0-100 */
  adherenceScore: number;
}

export interface WeightLog {
  id: number;
  userId: number;
  weightKg: number;
  date: string;
  /** @nullable */
  notes?: string | null;
  createdAt: string;
}

export interface WeightLogInput {
  weightKg: number;
  date: string;
  notes?: string;
}

export type MealPlanGoal = typeof MealPlanGoal[keyof typeof MealPlanGoal];


export const MealPlanGoal = {
  weight_loss: 'weight_loss',
  diabetes: 'diabetes',
  energy: 'energy',
  general: 'general',
} as const;

export type MealPlanEntryMealTime = typeof MealPlanEntryMealTime[keyof typeof MealPlanEntryMealTime];


export const MealPlanEntryMealTime = {
  breakfast: 'breakfast',
  lunch: 'lunch',
  dinner: 'dinner',
  snack: 'snack',
} as const;

export interface MealPlanEntry {
  id: number;
  planId: number;
  /**
     * @minimum 0
     * @maximum 6
     */
  dayOfWeek: number;
  mealTime: MealPlanEntryMealTime;
  foodName: string;
  /** @nullable */
  quantity?: string | null;
  /** @nullable */
  notes?: string | null;
}

export interface MealPlan {
  id: number;
  userId: number;
  title: string;
  /** @nullable */
  titleAr?: string | null;
  goal: MealPlanGoal;
  startDate: string;
  /** @nullable */
  endDate?: string | null;
  isActive?: boolean;
  /** @nullable */
  notes?: string | null;
  entries?: MealPlanEntry[];
  createdAt: string;
}

export type MealPlanInputGoal = typeof MealPlanInputGoal[keyof typeof MealPlanInputGoal];


export const MealPlanInputGoal = {
  weight_loss: 'weight_loss',
  diabetes: 'diabetes',
  energy: 'energy',
  general: 'general',
} as const;

export interface MealPlanInput {
  title: string;
  titleAr?: string;
  goal: MealPlanInputGoal;
  startDate: string;
  endDate?: string;
  notes?: string;
}

export type MealPlanUpdateGoal = typeof MealPlanUpdateGoal[keyof typeof MealPlanUpdateGoal];


export const MealPlanUpdateGoal = {
  weight_loss: 'weight_loss',
  diabetes: 'diabetes',
  energy: 'energy',
  general: 'general',
} as const;

export interface MealPlanUpdate {
  title?: string;
  titleAr?: string;
  goal?: MealPlanUpdateGoal;
  startDate?: string;
  endDate?: string;
  isActive?: boolean;
  notes?: string;
}

export interface Recipe {
  id: number;
  title: string;
  titleAr: string;
  category: string;
  goal: string;
  /** @nullable */
  imageUrl?: string | null;
  ingredients: string;
  instructions: string;
  /** @nullable */
  prepTimeMinutes?: number | null;
  /** @nullable */
  servings?: number | null;
  tags?: string[];
  createdAt: string;
}

export interface DashboardSummary {
  /** Consecutive days with logged meals */
  currentStreak: number;
  longestStreak: number;
  totalMealsLogged: number;
  tayyibAdherencePercent: number;
  weeklyWaterAvgMl: number;
  /** @nullable */
  currentWeight: number | null;
  /** @nullable */
  targetWeight: number | null;
  /** @nullable */
  activePlanTitle: string | null;
  recentEntries?: TrackerEntry[];
}

export interface ChartPoint {
  date: string;
  value: number;
}

export interface ProgressCharts {
  weightData: ChartPoint[];
  energyData: ChartPoint[];
  adherenceData: ChartPoint[];
  waterData: ChartPoint[];
}

export interface CalendarDay {
  date: string;
  mealCount: number;
  adherenceScore: number;
}

export type UserProfileGoal = typeof UserProfileGoal[keyof typeof UserProfileGoal];


export const UserProfileGoal = {
  weight_loss: 'weight_loss',
  diabetes: 'diabetes',
  energy: 'energy',
  general: 'general',
} as const;

export type UserProfileLanguage = typeof UserProfileLanguage[keyof typeof UserProfileLanguage];


export const UserProfileLanguage = {
  ar: 'ar',
  en: 'en',
} as const;

export interface UserProfile {
  id: number;
  userId: number;
  goal: UserProfileGoal;
  /** @nullable */
  targetWeight?: number | null;
  /** @nullable */
  currentWeight?: number | null;
  /** @nullable */
  heightCm?: number | null;
  /** @nullable */
  dateOfBirth?: string | null;
  /** @nullable */
  gender?: string | null;
  language: UserProfileLanguage;
  notificationsEnabled?: boolean;
  /** @nullable */
  fastingReminderTime?: string | null;
  /** @nullable */
  waterReminderIntervalHours?: number | null;
}

export type UserProfileUpdateGoal = typeof UserProfileUpdateGoal[keyof typeof UserProfileUpdateGoal];


export const UserProfileUpdateGoal = {
  weight_loss: 'weight_loss',
  diabetes: 'diabetes',
  energy: 'energy',
  general: 'general',
} as const;

export type UserProfileUpdateLanguage = typeof UserProfileUpdateLanguage[keyof typeof UserProfileUpdateLanguage];


export const UserProfileUpdateLanguage = {
  ar: 'ar',
  en: 'en',
} as const;

export interface UserProfileUpdate {
  goal?: UserProfileUpdateGoal;
  targetWeight?: number;
  currentWeight?: number;
  heightCm?: number;
  dateOfBirth?: string;
  gender?: string;
  language?: UserProfileUpdateLanguage;
  notificationsEnabled?: boolean;
  fastingReminderTime?: string;
  waterReminderIntervalHours?: number;
}

export type ListFoodsParams = {
category?: string;
status?: ListFoodsStatus;
search?: string;
page?: number;
limit?: number;
};

export type ListFoodsStatus = typeof ListFoodsStatus[keyof typeof ListFoodsStatus];


export const ListFoodsStatus = {
  tayyib: 'tayyib',
  khabeeth: 'khabeeth',
} as const;

export type ListTrackerEntriesParams = {
startDate?: string;
endDate?: string;
};

export type ListWeightLogsParams = {
days?: number;
};

export type ListRecipesParams = {
category?: string;
goal?: string;
search?: string;
};

export type GetProgressChartsParams = {
days?: number;
};

export type GetCalendarDataParams = {
year?: number;
month?: number;
};

