/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * Tayyibat Dietary System API — Dr. Dhia Al-Awadi
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AuthResponse,
  CalendarDay,
  DashboardSummary,
  Food,
  FoodCategory,
  FoodListResponse,
  GetCalendarDataParams,
  GetProgressChartsParams,
  HealthStatus,
  ListFoodsParams,
  ListRecipesParams,
  ListTrackerEntriesParams,
  ListWeightLogsParams,
  LoginInput,
  MealPlan,
  MealPlanInput,
  MealPlanUpdate,
  ProgressCharts,
  Recipe,
  RegisterInput,
  TodaySummary,
  TrackerEntry,
  TrackerEntryInput,
  TrackerEntryUpdate,
  User,
  UserProfile,
  UserProfileUpdate,
  WeightLog,
  WeightLogInput
} from './api.schemas';

import { customFetch } from './custom-fetch';
import type { ErrorType , BodyType } from './custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getHealthCheckUrl = () => {




  return `/api/healthz`
}

/**
 * @summary Health check
 */
export const healthCheck = async ( options?: RequestInit): Promise<HealthStatus> => {

  return customFetch<HealthStatus>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/api/healthz`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = ErrorType<unknown>


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getRegisterUrl = () => {




  return `/api/auth/register`
}

/**
 * @summary Register a new user
 */
export const register = async (registerInput: RegisterInput, options?: RequestInit): Promise<AuthResponse> => {

  return customFetch<AuthResponse>(getRegisterUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerInput,)
  }
);}




export const getRegisterMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: BodyType<RegisterInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: BodyType<RegisterInput>}, TContext> => {

const mutationKey = ['register'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof register>>, {data: BodyType<RegisterInput>}> = (props) => {
          const {data} = props ?? {};

          return  register(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RegisterMutationResult = NonNullable<Awaited<ReturnType<typeof register>>>
    export type RegisterMutationBody = BodyType<RegisterInput>
    export type RegisterMutationError = ErrorType<void>

    /**
 * @summary Register a new user
 */
export const useRegister = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof register>>, TError,{data: BodyType<RegisterInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof register>>,
        TError,
        {data: BodyType<RegisterInput>},
        TContext
      > => {
      return useMutation(getRegisterMutationOptions(options));
    }

export const getLoginUrl = () => {




  return `/api/auth/login`
}

/**
 * @summary Login
 */
export const login = async (loginInput: LoginInput, options?: RequestInit): Promise<AuthResponse> => {

  return customFetch<AuthResponse>(getLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginInput,)
  }
);}




export const getLoginMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<LoginInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<LoginInput>}, TContext> => {

const mutationKey = ['login'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof login>>, {data: BodyType<LoginInput>}> = (props) => {
          const {data} = props ?? {};

          return  login(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LoginMutationResult = NonNullable<Awaited<ReturnType<typeof login>>>
    export type LoginMutationBody = BodyType<LoginInput>
    export type LoginMutationError = ErrorType<void>

    /**
 * @summary Login
 */
export const useLogin = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof login>>, TError,{data: BodyType<LoginInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof login>>,
        TError,
        {data: BodyType<LoginInput>},
        TContext
      > => {
      return useMutation(getLoginMutationOptions(options));
    }

export const getLogoutUrl = () => {




  return `/api/auth/logout`
}

/**
 * @summary Logout
 */
export const logout = async ( options?: RequestInit): Promise<void> => {

  return customFetch<void>(getLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}




export const getLogoutMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext> => {

const mutationKey = ['logout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, void> = () => {


          return  logout(requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>

    export type LogoutMutationError = ErrorType<unknown>

    /**
 * @summary Logout
 */
export const useLogout = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof logout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getLogoutMutationOptions(options));
    }

export const getGetMeUrl = () => {




  return `/api/auth/me`
}

/**
 * @summary Get current user
 */
export const getMe = async ( options?: RequestInit): Promise<User> => {

  return customFetch<User>(getGetMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMeQueryKey = () => {
    return [
    `/api/auth/me`
    ] as const;
    }


export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<void>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = ErrorType<void>


/**
 * @summary Get current user
 */

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<void>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListFoodsUrl = (params?: ListFoodsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/foods?${stringifiedParams}` : `/api/foods`
}

/**
 * @summary List all foods with optional filters
 */
export const listFoods = async (params?: ListFoodsParams, options?: RequestInit): Promise<FoodListResponse> => {

  return customFetch<FoodListResponse>(getListFoodsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListFoodsQueryKey = (params?: ListFoodsParams,) => {
    return [
    `/api/foods`, ...(params ? [params] : [])
    ] as const;
    }


export const getListFoodsQueryOptions = <TData = Awaited<ReturnType<typeof listFoods>>, TError = ErrorType<unknown>>(params?: ListFoodsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listFoods>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFoodsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFoods>>> = ({ signal }) => listFoods(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFoods>>, TError, TData> & { queryKey: QueryKey }
}

export type ListFoodsQueryResult = NonNullable<Awaited<ReturnType<typeof listFoods>>>
export type ListFoodsQueryError = ErrorType<unknown>


/**
 * @summary List all foods with optional filters
 */

export function useListFoods<TData = Awaited<ReturnType<typeof listFoods>>, TError = ErrorType<unknown>>(
 params?: ListFoodsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listFoods>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListFoodsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListFoodCategoriesUrl = () => {




  return `/api/foods/categories`
}

/**
 * @summary List all food categories with counts
 */
export const listFoodCategories = async ( options?: RequestInit): Promise<FoodCategory[]> => {

  return customFetch<FoodCategory[]>(getListFoodCategoriesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListFoodCategoriesQueryKey = () => {
    return [
    `/api/foods/categories`
    ] as const;
    }


export const getListFoodCategoriesQueryOptions = <TData = Awaited<ReturnType<typeof listFoodCategories>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listFoodCategories>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListFoodCategoriesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listFoodCategories>>> = ({ signal }) => listFoodCategories({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listFoodCategories>>, TError, TData> & { queryKey: QueryKey }
}

export type ListFoodCategoriesQueryResult = NonNullable<Awaited<ReturnType<typeof listFoodCategories>>>
export type ListFoodCategoriesQueryError = ErrorType<unknown>


/**
 * @summary List all food categories with counts
 */

export function useListFoodCategories<TData = Awaited<ReturnType<typeof listFoodCategories>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listFoodCategories>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListFoodCategoriesQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetFoodUrl = (id: number,) => {




  return `/api/foods/${id}`
}

/**
 * @summary Get a single food item
 */
export const getFood = async (id: number, options?: RequestInit): Promise<Food> => {

  return customFetch<Food>(getGetFoodUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetFoodQueryKey = (id: number,) => {
    return [
    `/api/foods/${id}`
    ] as const;
    }


export const getGetFoodQueryOptions = <TData = Awaited<ReturnType<typeof getFood>>, TError = ErrorType<void>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getFood>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFoodQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFood>>> = ({ signal }) => getFood(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFood>>, TError, TData> & { queryKey: QueryKey }
}

export type GetFoodQueryResult = NonNullable<Awaited<ReturnType<typeof getFood>>>
export type GetFoodQueryError = ErrorType<void>


/**
 * @summary Get a single food item
 */

export function useGetFood<TData = Awaited<ReturnType<typeof getFood>>, TError = ErrorType<void>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getFood>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetFoodQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListTrackerEntriesUrl = (params?: ListTrackerEntriesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/tracker/entries?${stringifiedParams}` : `/api/tracker/entries`
}

/**
 * @summary List tracker entries for a date range
 */
export const listTrackerEntries = async (params?: ListTrackerEntriesParams, options?: RequestInit): Promise<TrackerEntry[]> => {

  return customFetch<TrackerEntry[]>(getListTrackerEntriesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListTrackerEntriesQueryKey = (params?: ListTrackerEntriesParams,) => {
    return [
    `/api/tracker/entries`, ...(params ? [params] : [])
    ] as const;
    }


export const getListTrackerEntriesQueryOptions = <TData = Awaited<ReturnType<typeof listTrackerEntries>>, TError = ErrorType<unknown>>(params?: ListTrackerEntriesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listTrackerEntries>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTrackerEntriesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTrackerEntries>>> = ({ signal }) => listTrackerEntries(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTrackerEntries>>, TError, TData> & { queryKey: QueryKey }
}

export type ListTrackerEntriesQueryResult = NonNullable<Awaited<ReturnType<typeof listTrackerEntries>>>
export type ListTrackerEntriesQueryError = ErrorType<unknown>


/**
 * @summary List tracker entries for a date range
 */

export function useListTrackerEntries<TData = Awaited<ReturnType<typeof listTrackerEntries>>, TError = ErrorType<unknown>>(
 params?: ListTrackerEntriesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listTrackerEntries>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListTrackerEntriesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreateTrackerEntryUrl = () => {




  return `/api/tracker/entries`
}

/**
 * @summary Log a meal or habit entry
 */
export const createTrackerEntry = async (trackerEntryInput: TrackerEntryInput, options?: RequestInit): Promise<TrackerEntry> => {

  return customFetch<TrackerEntry>(getCreateTrackerEntryUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      trackerEntryInput,)
  }
);}




export const getCreateTrackerEntryMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTrackerEntry>>, TError,{data: BodyType<TrackerEntryInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createTrackerEntry>>, TError,{data: BodyType<TrackerEntryInput>}, TContext> => {

const mutationKey = ['createTrackerEntry'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTrackerEntry>>, {data: BodyType<TrackerEntryInput>}> = (props) => {
          const {data} = props ?? {};

          return  createTrackerEntry(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateTrackerEntryMutationResult = NonNullable<Awaited<ReturnType<typeof createTrackerEntry>>>
    export type CreateTrackerEntryMutationBody = BodyType<TrackerEntryInput>
    export type CreateTrackerEntryMutationError = ErrorType<unknown>

    /**
 * @summary Log a meal or habit entry
 */
export const useCreateTrackerEntry = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTrackerEntry>>, TError,{data: BodyType<TrackerEntryInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createTrackerEntry>>,
        TError,
        {data: BodyType<TrackerEntryInput>},
        TContext
      > => {
      return useMutation(getCreateTrackerEntryMutationOptions(options));
    }

export const getUpdateTrackerEntryUrl = (id: number,) => {




  return `/api/tracker/entries/${id}`
}

/**
 * @summary Update a tracker entry
 */
export const updateTrackerEntry = async (id: number,
    trackerEntryUpdate: TrackerEntryUpdate, options?: RequestInit): Promise<TrackerEntry> => {

  return customFetch<TrackerEntry>(getUpdateTrackerEntryUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      trackerEntryUpdate,)
  }
);}




export const getUpdateTrackerEntryMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTrackerEntry>>, TError,{id: number;data: BodyType<TrackerEntryUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateTrackerEntry>>, TError,{id: number;data: BodyType<TrackerEntryUpdate>}, TContext> => {

const mutationKey = ['updateTrackerEntry'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTrackerEntry>>, {id: number;data: BodyType<TrackerEntryUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateTrackerEntry(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateTrackerEntryMutationResult = NonNullable<Awaited<ReturnType<typeof updateTrackerEntry>>>
    export type UpdateTrackerEntryMutationBody = BodyType<TrackerEntryUpdate>
    export type UpdateTrackerEntryMutationError = ErrorType<unknown>

    /**
 * @summary Update a tracker entry
 */
export const useUpdateTrackerEntry = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTrackerEntry>>, TError,{id: number;data: BodyType<TrackerEntryUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateTrackerEntry>>,
        TError,
        {id: number;data: BodyType<TrackerEntryUpdate>},
        TContext
      > => {
      return useMutation(getUpdateTrackerEntryMutationOptions(options));
    }

export const getDeleteTrackerEntryUrl = (id: number,) => {




  return `/api/tracker/entries/${id}`
}

/**
 * @summary Delete a tracker entry
 */
export const deleteTrackerEntry = async (id: number, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeleteTrackerEntryUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteTrackerEntryMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTrackerEntry>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteTrackerEntry>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteTrackerEntry'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteTrackerEntry>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteTrackerEntry(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteTrackerEntryMutationResult = NonNullable<Awaited<ReturnType<typeof deleteTrackerEntry>>>

    export type DeleteTrackerEntryMutationError = ErrorType<unknown>

    /**
 * @summary Delete a tracker entry
 */
export const useDeleteTrackerEntry = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteTrackerEntry>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteTrackerEntry>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteTrackerEntryMutationOptions(options));
    }

export const getGetTodaysSummaryUrl = () => {




  return `/api/tracker/today`
}

/**
 * @summary Get today's tracking summary (meals, fasting, water, hunger)
 */
export const getTodaysSummary = async ( options?: RequestInit): Promise<TodaySummary> => {

  return customFetch<TodaySummary>(getGetTodaysSummaryUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTodaysSummaryQueryKey = () => {
    return [
    `/api/tracker/today`
    ] as const;
    }


export const getGetTodaysSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getTodaysSummary>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTodaysSummary>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTodaysSummaryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodaysSummary>>> = ({ signal }) => getTodaysSummary({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTodaysSummary>>, TError, TData> & { queryKey: QueryKey }
}

export type GetTodaysSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getTodaysSummary>>>
export type GetTodaysSummaryQueryError = ErrorType<unknown>


/**
 * @summary Get today's tracking summary (meals, fasting, water, hunger)
 */

export function useGetTodaysSummary<TData = Awaited<ReturnType<typeof getTodaysSummary>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getTodaysSummary>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetTodaysSummaryQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getListWeightLogsUrl = (params?: ListWeightLogsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/tracker/weight?${stringifiedParams}` : `/api/tracker/weight`
}

/**
 * @summary List weight log entries
 */
export const listWeightLogs = async (params?: ListWeightLogsParams, options?: RequestInit): Promise<WeightLog[]> => {

  return customFetch<WeightLog[]>(getListWeightLogsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListWeightLogsQueryKey = (params?: ListWeightLogsParams,) => {
    return [
    `/api/tracker/weight`, ...(params ? [params] : [])
    ] as const;
    }


export const getListWeightLogsQueryOptions = <TData = Awaited<ReturnType<typeof listWeightLogs>>, TError = ErrorType<unknown>>(params?: ListWeightLogsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listWeightLogs>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListWeightLogsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listWeightLogs>>> = ({ signal }) => listWeightLogs(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listWeightLogs>>, TError, TData> & { queryKey: QueryKey }
}

export type ListWeightLogsQueryResult = NonNullable<Awaited<ReturnType<typeof listWeightLogs>>>
export type ListWeightLogsQueryError = ErrorType<unknown>


/**
 * @summary List weight log entries
 */

export function useListWeightLogs<TData = Awaited<ReturnType<typeof listWeightLogs>>, TError = ErrorType<unknown>>(
 params?: ListWeightLogsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listWeightLogs>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListWeightLogsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreateWeightLogUrl = () => {




  return `/api/tracker/weight`
}

/**
 * @summary Log a weight entry
 */
export const createWeightLog = async (weightLogInput: WeightLogInput, options?: RequestInit): Promise<WeightLog> => {

  return customFetch<WeightLog>(getCreateWeightLogUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      weightLogInput,)
  }
);}




export const getCreateWeightLogMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWeightLog>>, TError,{data: BodyType<WeightLogInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createWeightLog>>, TError,{data: BodyType<WeightLogInput>}, TContext> => {

const mutationKey = ['createWeightLog'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createWeightLog>>, {data: BodyType<WeightLogInput>}> = (props) => {
          const {data} = props ?? {};

          return  createWeightLog(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateWeightLogMutationResult = NonNullable<Awaited<ReturnType<typeof createWeightLog>>>
    export type CreateWeightLogMutationBody = BodyType<WeightLogInput>
    export type CreateWeightLogMutationError = ErrorType<unknown>

    /**
 * @summary Log a weight entry
 */
export const useCreateWeightLog = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createWeightLog>>, TError,{data: BodyType<WeightLogInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createWeightLog>>,
        TError,
        {data: BodyType<WeightLogInput>},
        TContext
      > => {
      return useMutation(getCreateWeightLogMutationOptions(options));
    }

export const getListMealPlansUrl = () => {




  return `/api/plans`
}

/**
 * @summary List user's meal plans
 */
export const listMealPlans = async ( options?: RequestInit): Promise<MealPlan[]> => {

  return customFetch<MealPlan[]>(getListMealPlansUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListMealPlansQueryKey = () => {
    return [
    `/api/plans`
    ] as const;
    }


export const getListMealPlansQueryOptions = <TData = Awaited<ReturnType<typeof listMealPlans>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listMealPlans>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListMealPlansQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listMealPlans>>> = ({ signal }) => listMealPlans({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listMealPlans>>, TError, TData> & { queryKey: QueryKey }
}

export type ListMealPlansQueryResult = NonNullable<Awaited<ReturnType<typeof listMealPlans>>>
export type ListMealPlansQueryError = ErrorType<unknown>


/**
 * @summary List user's meal plans
 */

export function useListMealPlans<TData = Awaited<ReturnType<typeof listMealPlans>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listMealPlans>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListMealPlansQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getCreateMealPlanUrl = () => {




  return `/api/plans`
}

/**
 * @summary Create a new meal plan
 */
export const createMealPlan = async (mealPlanInput: MealPlanInput, options?: RequestInit): Promise<MealPlan> => {

  return customFetch<MealPlan>(getCreateMealPlanUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      mealPlanInput,)
  }
);}




export const getCreateMealPlanMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMealPlan>>, TError,{data: BodyType<MealPlanInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof createMealPlan>>, TError,{data: BodyType<MealPlanInput>}, TContext> => {

const mutationKey = ['createMealPlan'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMealPlan>>, {data: BodyType<MealPlanInput>}> = (props) => {
          const {data} = props ?? {};

          return  createMealPlan(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateMealPlanMutationResult = NonNullable<Awaited<ReturnType<typeof createMealPlan>>>
    export type CreateMealPlanMutationBody = BodyType<MealPlanInput>
    export type CreateMealPlanMutationError = ErrorType<unknown>

    /**
 * @summary Create a new meal plan
 */
export const useCreateMealPlan = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMealPlan>>, TError,{data: BodyType<MealPlanInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createMealPlan>>,
        TError,
        {data: BodyType<MealPlanInput>},
        TContext
      > => {
      return useMutation(getCreateMealPlanMutationOptions(options));
    }

export const getGetMealPlanUrl = (id: number,) => {




  return `/api/plans/${id}`
}

/**
 * @summary Get a specific meal plan with its entries
 */
export const getMealPlan = async (id: number, options?: RequestInit): Promise<MealPlan> => {

  return customFetch<MealPlan>(getGetMealPlanUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMealPlanQueryKey = (id: number,) => {
    return [
    `/api/plans/${id}`
    ] as const;
    }


export const getGetMealPlanQueryOptions = <TData = Awaited<ReturnType<typeof getMealPlan>>, TError = ErrorType<unknown>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMealPlan>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMealPlanQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMealPlan>>> = ({ signal }) => getMealPlan(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMealPlan>>, TError, TData> & { queryKey: QueryKey }
}

export type GetMealPlanQueryResult = NonNullable<Awaited<ReturnType<typeof getMealPlan>>>
export type GetMealPlanQueryError = ErrorType<unknown>


/**
 * @summary Get a specific meal plan with its entries
 */

export function useGetMealPlan<TData = Awaited<ReturnType<typeof getMealPlan>>, TError = ErrorType<unknown>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getMealPlan>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetMealPlanQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getUpdateMealPlanUrl = (id: number,) => {




  return `/api/plans/${id}`
}

/**
 * @summary Update a meal plan
 */
export const updateMealPlan = async (id: number,
    mealPlanUpdate: MealPlanUpdate, options?: RequestInit): Promise<MealPlan> => {

  return customFetch<MealPlan>(getUpdateMealPlanUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      mealPlanUpdate,)
  }
);}




export const getUpdateMealPlanMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMealPlan>>, TError,{id: number;data: BodyType<MealPlanUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateMealPlan>>, TError,{id: number;data: BodyType<MealPlanUpdate>}, TContext> => {

const mutationKey = ['updateMealPlan'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMealPlan>>, {id: number;data: BodyType<MealPlanUpdate>}> = (props) => {
          const {id,data} = props ?? {};

          return  updateMealPlan(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateMealPlanMutationResult = NonNullable<Awaited<ReturnType<typeof updateMealPlan>>>
    export type UpdateMealPlanMutationBody = BodyType<MealPlanUpdate>
    export type UpdateMealPlanMutationError = ErrorType<unknown>

    /**
 * @summary Update a meal plan
 */
export const useUpdateMealPlan = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMealPlan>>, TError,{id: number;data: BodyType<MealPlanUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateMealPlan>>,
        TError,
        {id: number;data: BodyType<MealPlanUpdate>},
        TContext
      > => {
      return useMutation(getUpdateMealPlanMutationOptions(options));
    }

export const getDeleteMealPlanUrl = (id: number,) => {




  return `/api/plans/${id}`
}

/**
 * @summary Delete a meal plan
 */
export const deleteMealPlan = async (id: number, options?: RequestInit): Promise<void> => {

  return customFetch<void>(getDeleteMealPlanUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteMealPlanMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMealPlan>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteMealPlan>>, TError,{id: number}, TContext> => {

const mutationKey = ['deleteMealPlan'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMealPlan>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  deleteMealPlan(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteMealPlanMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMealPlan>>>

    export type DeleteMealPlanMutationError = ErrorType<unknown>

    /**
 * @summary Delete a meal plan
 */
export const useDeleteMealPlan = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMealPlan>>, TError,{id: number}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteMealPlan>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getDeleteMealPlanMutationOptions(options));
    }

export const getListRecipesUrl = (params?: ListRecipesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/recipes?${stringifiedParams}` : `/api/recipes`
}

/**
 * @summary List recipes with filters
 */
export const listRecipes = async (params?: ListRecipesParams, options?: RequestInit): Promise<Recipe[]> => {

  return customFetch<Recipe[]>(getListRecipesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListRecipesQueryKey = (params?: ListRecipesParams,) => {
    return [
    `/api/recipes`, ...(params ? [params] : [])
    ] as const;
    }


export const getListRecipesQueryOptions = <TData = Awaited<ReturnType<typeof listRecipes>>, TError = ErrorType<unknown>>(params?: ListRecipesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listRecipes>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRecipesQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRecipes>>> = ({ signal }) => listRecipes(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRecipes>>, TError, TData> & { queryKey: QueryKey }
}

export type ListRecipesQueryResult = NonNullable<Awaited<ReturnType<typeof listRecipes>>>
export type ListRecipesQueryError = ErrorType<unknown>


/**
 * @summary List recipes with filters
 */

export function useListRecipes<TData = Awaited<ReturnType<typeof listRecipes>>, TError = ErrorType<unknown>>(
 params?: ListRecipesParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof listRecipes>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getListRecipesQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetRecipeUrl = (id: number,) => {




  return `/api/recipes/${id}`
}

/**
 * @summary Get a single recipe
 */
export const getRecipe = async (id: number, options?: RequestInit): Promise<Recipe> => {

  return customFetch<Recipe>(getGetRecipeUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetRecipeQueryKey = (id: number,) => {
    return [
    `/api/recipes/${id}`
    ] as const;
    }


export const getGetRecipeQueryOptions = <TData = Awaited<ReturnType<typeof getRecipe>>, TError = ErrorType<void>>(id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRecipe>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRecipeQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRecipe>>> = ({ signal }) => getRecipe(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRecipe>>, TError, TData> & { queryKey: QueryKey }
}

export type GetRecipeQueryResult = NonNullable<Awaited<ReturnType<typeof getRecipe>>>
export type GetRecipeQueryError = ErrorType<void>


/**
 * @summary Get a single recipe
 */

export function useGetRecipe<TData = Awaited<ReturnType<typeof getRecipe>>, TError = ErrorType<void>>(
 id: number, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getRecipe>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetRecipeQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetDashboardSummaryUrl = () => {




  return `/api/dashboard/summary`
}

/**
 * @summary Get dashboard overview (streaks, totals, adherence)
 */
export const getDashboardSummary = async ( options?: RequestInit): Promise<DashboardSummary> => {

  return customFetch<DashboardSummary>(getGetDashboardSummaryUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDashboardSummaryQueryKey = () => {
    return [
    `/api/dashboard/summary`
    ] as const;
    }


export const getGetDashboardSummaryQueryOptions = <TData = Awaited<ReturnType<typeof getDashboardSummary>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDashboardSummary>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardSummaryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboardSummary>>> = ({ signal }) => getDashboardSummary({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDashboardSummary>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDashboardSummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboardSummary>>>
export type GetDashboardSummaryQueryError = ErrorType<unknown>


/**
 * @summary Get dashboard overview (streaks, totals, adherence)
 */

export function useGetDashboardSummary<TData = Awaited<ReturnType<typeof getDashboardSummary>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDashboardSummary>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDashboardSummaryQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetProgressChartsUrl = (params?: GetProgressChartsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/dashboard/progress?${stringifiedParams}` : `/api/dashboard/progress`
}

/**
 * @summary Get chart data for weight, energy, and adherence over time
 */
export const getProgressCharts = async (params?: GetProgressChartsParams, options?: RequestInit): Promise<ProgressCharts> => {

  return customFetch<ProgressCharts>(getGetProgressChartsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetProgressChartsQueryKey = (params?: GetProgressChartsParams,) => {
    return [
    `/api/dashboard/progress`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetProgressChartsQueryOptions = <TData = Awaited<ReturnType<typeof getProgressCharts>>, TError = ErrorType<unknown>>(params?: GetProgressChartsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getProgressCharts>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProgressChartsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProgressCharts>>> = ({ signal }) => getProgressCharts(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProgressCharts>>, TError, TData> & { queryKey: QueryKey }
}

export type GetProgressChartsQueryResult = NonNullable<Awaited<ReturnType<typeof getProgressCharts>>>
export type GetProgressChartsQueryError = ErrorType<unknown>


/**
 * @summary Get chart data for weight, energy, and adherence over time
 */

export function useGetProgressCharts<TData = Awaited<ReturnType<typeof getProgressCharts>>, TError = ErrorType<unknown>>(
 params?: GetProgressChartsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getProgressCharts>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetProgressChartsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetCalendarDataUrl = (params?: GetCalendarDataParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/dashboard/calendar?${stringifiedParams}` : `/api/dashboard/calendar`
}

/**
 * @summary Get calendar heatmap data for meal tracking adherence
 */
export const getCalendarData = async (params?: GetCalendarDataParams, options?: RequestInit): Promise<CalendarDay[]> => {

  return customFetch<CalendarDay[]>(getGetCalendarDataUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCalendarDataQueryKey = (params?: GetCalendarDataParams,) => {
    return [
    `/api/dashboard/calendar`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetCalendarDataQueryOptions = <TData = Awaited<ReturnType<typeof getCalendarData>>, TError = ErrorType<unknown>>(params?: GetCalendarDataParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCalendarData>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCalendarDataQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCalendarData>>> = ({ signal }) => getCalendarData(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCalendarData>>, TError, TData> & { queryKey: QueryKey }
}

export type GetCalendarDataQueryResult = NonNullable<Awaited<ReturnType<typeof getCalendarData>>>
export type GetCalendarDataQueryError = ErrorType<unknown>


/**
 * @summary Get calendar heatmap data for meal tracking adherence
 */

export function useGetCalendarData<TData = Awaited<ReturnType<typeof getCalendarData>>, TError = ErrorType<unknown>>(
 params?: GetCalendarDataParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getCalendarData>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetCalendarDataQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetProfileUrl = () => {




  return `/api/profile`
}

/**
 * @summary Get user profile and goals
 */
export const getProfile = async ( options?: RequestInit): Promise<UserProfile> => {

  return customFetch<UserProfile>(getGetProfileUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetProfileQueryKey = () => {
    return [
    `/api/profile`
    ] as const;
    }


export const getGetProfileQueryOptions = <TData = Awaited<ReturnType<typeof getProfile>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getProfile>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProfileQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProfile>>> = ({ signal }) => getProfile({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProfile>>, TError, TData> & { queryKey: QueryKey }
}

export type GetProfileQueryResult = NonNullable<Awaited<ReturnType<typeof getProfile>>>
export type GetProfileQueryError = ErrorType<unknown>


/**
 * @summary Get user profile and goals
 */

export function useGetProfile<TData = Awaited<ReturnType<typeof getProfile>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getProfile>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetProfileQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getUpdateProfileUrl = () => {




  return `/api/profile`
}

/**
 * @summary Update user profile and goals
 */
export const updateProfile = async (userProfileUpdate: UserProfileUpdate, options?: RequestInit): Promise<UserProfile> => {

  return customFetch<UserProfile>(getUpdateProfileUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userProfileUpdate,)
  }
);}




export const getUpdateProfileMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProfile>>, TError,{data: BodyType<UserProfileUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof updateProfile>>, TError,{data: BodyType<UserProfileUpdate>}, TContext> => {

const mutationKey = ['updateProfile'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateProfile>>, {data: BodyType<UserProfileUpdate>}> = (props) => {
          const {data} = props ?? {};

          return  updateProfile(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateProfileMutationResult = NonNullable<Awaited<ReturnType<typeof updateProfile>>>
    export type UpdateProfileMutationBody = BodyType<UserProfileUpdate>
    export type UpdateProfileMutationError = ErrorType<unknown>

    /**
 * @summary Update user profile and goals
 */
export const useUpdateProfile = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateProfile>>, TError,{data: BodyType<UserProfileUpdate>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateProfile>>,
        TError,
        {data: BodyType<UserProfileUpdate>},
        TContext
      > => {
      return useMutation(getUpdateProfileMutationOptions(options));
    }

